#!/bin/bash -e

## Limit dhclient interfaces:
# By default, dhclient will send DHCP-DISCOVER packets on all available interfaces. Since we will be adding a number of virtual interfaces, none of which will respond to DHCP requests, we will limit dhclient to the ethernet and wifi interfaces.

[ -e $(dirname $0)/functions ] && source $(dirname $0)/functions

CONF="/etc/dhcp/dhclient.conf"

if [ -e ${CONF} ]; then
  grep -q '# limit to interfaces' ${CONF}
  if [ $? -ne 0 ]; then
    info "Limiting dhclient interfaces ..."
    LINKS=$(ip link | awk -F: '$0 !~ "lo|vi|ve|lx|^[^0-9]"{print $2}')
    echo "# limit to interfaces" | sudo tee -a ${CONF}
    for i in $LINKS; do
      echo "interface \"$i\" { }" | sudo tee -a ${CONF}
    done
  else
    info "Skipping dhclient configuration ..."
  fi
fi

