#!/bin/bash -e

info()    { echo -e "INFO [$(basename $0)]: $@"; }

# Initialize LXC/LXD network vars:

[ -e /etc/default/lxc-net ] && source /etc/default/lxc-net

LXD_BRIDGE=$(lxc network list |  awk '/bridge.*\|.*YES/ { print $2 }')
LXD_NETWORK=$(lxc network get $LXD_BRIDGE ipv4.address)
LXD_ADDR=${LXD_NETWORK%/*}

# Configure DnsMasq:

if [ -d /etc/NetworkManager/dnsmasq.d ]; then
  CONF="/etc/NetworkManager/dnsmasq.d/dnsmasq.conf"
else
  CONF="/etc/dnsmasq.d/dnsmasq.conf"
fi

if [ ! -e ${CONF} -o ${UPDATE} = true ]; then
  info "Creating ${CONF} ..."
  cat << EOT | sudo tee ${CONF}
# Configuration file for dnsmasq.
# ${CONF}
#
bind-interfaces
user=dnsmasq
group=dnsmasq

server=/lxd/${LXD_ADDR}
rev-server=${LXD_NETWORK},${LXD_ADDR}
server=/lxc/${LXC_ADDR}
rev-server=${LXC_NETWORK},${LXC_ADDR}

no-poll
neg-ttl=3600
cache-size=1000
dns-forward-max=1000

addn-hosts=/etc/hosts.dnsmasq
EOT
else
  info "Skipping ${CONF} ..."
fi

