#!/bin/bash -e

[ -e $(dirname $0)/functions ] && source $(dirname $0)/functions

# Kernel Preparation:

# Edit /etc/default/grub and append 'swapaccount=1' to the GRUB_CMDLINE_LINUX_DEFAULT line so it reads;
# GRUB_CMDLINE_LINUX_DEFAULT="quiet splash swapaccount=1"

CONF="/etc/default/grub"
if [ -e ${CONF} ]; then
  grep -q 'GRUB_CMDLINE_LINUX_DEFAULT.*swapaccount=' ${CONF}
  if [ $? -ne 0 ]; then
    info "Updating Grub Config"
    sudo sed -i '/GRUB_CMDLINE_LINUX_DEFAULT/ s/"\(.*\)"/"\1 swapaccount=1"/' ${CONF}
    sudo update-grub
  else
    info "Skipping Grub Update"
  fi
else
  info "Skipping Grub Update"
fi

