#!/bin/bash -e

# Allow packet forwarding in host

CONF="/etc/sysctl.conf"

if ! grep -qs "^# Enable packet forwarding" ${CONF}; then
  info "Updating /etc/sysctl.conf ..."
  cat << EOT | sudo tee -a ${CONF}
# Enable packet forwarding for IPv4
net.ipv4.conf.all.forwarding = 1
#
# Enable packet forwarding for IPv6
#  Enabling this option disables Stateless Address Autoconfiguration
#  based on Router Advertisements for this host
net.ipv6.conf.all.forwarding = 1
#
EOT
fi

# Activate sysctl config changes
sudo service procps start

